// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: protos/helloctl/service_helloctl.proto

package helloctl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloCtlClient is the client API for HelloCtl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloCtlClient interface {
	// 说Hello
	SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error)
}

type helloCtlClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloCtlClient(cc grpc.ClientConnInterface) HelloCtlClient {
	return &helloCtlClient{cc}
}

func (c *helloCtlClient) SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error) {
	out := new(SayHelloResp)
	err := c.cc.Invoke(ctx, "/helloctl.HelloCtl/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloCtlServer is the server API for HelloCtl service.
// All implementations should embed UnimplementedHelloCtlServer
// for forward compatibility
type HelloCtlServer interface {
	// 说Hello
	SayHello(context.Context, *SayHelloReq) (*SayHelloResp, error)
}

// UnimplementedHelloCtlServer should be embedded to have forward compatible implementations.
type UnimplementedHelloCtlServer struct {
}

func (UnimplementedHelloCtlServer) SayHello(context.Context, *SayHelloReq) (*SayHelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafeHelloCtlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloCtlServer will
// result in compilation errors.
type UnsafeHelloCtlServer interface {
	mustEmbedUnimplementedHelloCtlServer()
}

func RegisterHelloCtlServer(s grpc.ServiceRegistrar, srv HelloCtlServer) {
	s.RegisterService(&HelloCtl_ServiceDesc, srv)
}

func _HelloCtl_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloCtlServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloctl.HelloCtl/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloCtlServer).SayHello(ctx, req.(*SayHelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloCtl_ServiceDesc is the grpc.ServiceDesc for HelloCtl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloCtl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloctl.HelloCtl",
	HandlerType: (*HelloCtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloCtl_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/helloctl/service_helloctl.proto",
}
