<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloctl/hello.proto

namespace GPBMetadata\Protos\Helloctl;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ù
protos/helloctl/hello.protohelloctl"(
SayHelloReq
name (	
age ("g
SayHelloResp
code (
message (	
log_id (	(
data (2.helloctl.SayHelloRespData"\'
SayHelloRespData
access_time (BZ
.;helloctlbproto3'
        , true);

        static::$is_initialized = true;
    }
}

