<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloctlgateway/hello.proto

namespace Helloctlgateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>helloctlgateway.SayHelloResp</code>
 */
class SayHelloResp extends \Google\Protobuf\Internal\Message
{
    /**
     * 状态码。0成功；非0失败
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * 状态码说明
     *
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * 日志ID
     *
     * Generated from protobuf field <code>string log_id = 3;</code>
     */
    protected $log_id = '';
    /**
     * 数据
     *
     * Generated from protobuf field <code>.helloctlgateway.SayHelloRespData data = 4;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           状态码。0成功；非0失败
     *     @type string $message
     *           状态码说明
     *     @type string $log_id
     *           日志ID
     *     @type \Helloctlgateway\SayHelloRespData $data
     *           数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Helloctlgateway\Hello::initOnce();
        parent::__construct($data);
    }

    /**
     * 状态码。0成功；非0失败
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 状态码。0成功；非0失败
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * 状态码说明
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * 状态码说明
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * 日志ID
     *
     * Generated from protobuf field <code>string log_id = 3;</code>
     * @return string
     */
    public function getLogId()
    {
        return $this->log_id;
    }

    /**
     * 日志ID
     *
     * Generated from protobuf field <code>string log_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLogId($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_id = $var;

        return $this;
    }

    /**
     * 数据
     *
     * Generated from protobuf field <code>.helloctlgateway.SayHelloRespData data = 4;</code>
     * @return \Helloctlgateway\SayHelloRespData|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * 数据
     *
     * Generated from protobuf field <code>.helloctlgateway.SayHelloRespData data = 4;</code>
     * @param \Helloctlgateway\SayHelloRespData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Helloctlgateway\SayHelloRespData::class);
        $this->data = $var;

        return $this;
    }

}

