<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloctlgateway/hello.proto

namespace Helloctlgateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>helloctlgateway.SayHelloRespData</code>
 */
class SayHelloRespData extends \Google\Protobuf\Internal\Message
{
    /**
     * 访问时间
     *
     * Generated from protobuf field <code>int64 access_time = 1;</code>
     */
    protected $access_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $access_time
     *           访问时间
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Helloctlgateway\Hello::initOnce();
        parent::__construct($data);
    }

    /**
     * 访问时间
     *
     * Generated from protobuf field <code>int64 access_time = 1;</code>
     * @return int|string
     */
    public function getAccessTime()
    {
        return $this->access_time;
    }

    /**
     * 访问时间
     *
     * Generated from protobuf field <code>int64 access_time = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccessTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->access_time = $var;

        return $this;
    }

}

