<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloctlgateway/hello.proto

namespace GPBMetadata\Protos\Helloctlgateway;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
–
"protos/helloctlgateway/hello.protohelloctlgateway"(
SayHelloReq
name (	
age ("n
SayHelloResp
code (
message (	
log_id (	/
data (2!.helloctlgateway.SayHelloRespData"\'
SayHelloRespData
access_time (BZ./;helloctlgatewaybproto3'
        , true);

        static::$is_initialized = true;
    }
}

